##################################
### KeePass4Web related config ###
##################################

# where to get keepass database from
# use 'Filesystem' for a simple file in the local filesystem
db_backend: 'Filesystem'

# backend to authenticate users before anything else
# available: None, LDAP
# None is only useful in single-user environments
auth_backend: 'Test'

# whether to use auth_backend credentials for database backend provider (if backend requires authentication)
auth_reuse_cred: 0

### Database backends ###

# file specific configuration, db_backend = 'Filesystem'
Filesystem:
    #db_location: '/opt/keepass4web/db.kdbx'
    db_location: '/media/data/Seafile/Sicher/Keepass/test/db.kdbx'
    # optional, storing key files on the filesystem is not recommended
    # keyfile_location: '/opt/keepass4web/db.kdbx'

### Authentication backends ###

# ldap specific configuration, auth_backend = 'LDAP'
LDAP:
    uri:    'ldap://127.0.0.1:389'
    scope:  'subtree'
    base_dn: 'OU=People,DC=example,DC=org'
    filter: '(&(objectClass=inetOrgPerson)(memberOf=CN=keepass,OU=groups,DC=example,DC=org))'

    # (unique) ldap attribute for user login
    # Active Directory: sAMAccountName or userPrincipalName
    # openLDAP/389 Directory Server/etc: uid
    login_attribute: 'uid'

    # ldap bind DN and password, leave empty for anonymous bind
    bind:     'CN=ldap-read,OU=Special Users,DC=example,DC=org'
    password: ''

    # TODO:
    # ldap attribute containing the keepass database or keyfile (per user), dependent on db backend
    # leave empty to use static db_location from above
    database_attribute: 'keePass'
    # key file location attribute
    keyfile_attribute:  'keePassKeyFile'


# time till database gets closed (user idle time)
# user will have to reenter database password/keyfile
db_session_timeout: '10 minutes'
# interval to watch for user auth_backend changes (to present proper login page, even when user is idling)
auth_check_interval: '1 hour 5 minutes'
# segment size in kilobytes to request
ipc_segment_size: 64
# SysV IPC key, usually only needs change if it clashes with another application
ipc_id: 3294967296
# type of keyring used for Kernel::Keyring
# see "man keyctl"
keyring_session: '@s'
# whether to include files and history in cached database
# disabling this can speed up the initial loading of the database and decrease memory in IPC
hist_and_bin: true
# whether to include custom icons in shared memory
# disable to increase performance and save memory+bandwidth
custom_icons: true
# webinterface: maximum open tree levels on load
toggled_levels: 3

search:
  # fields to search for matching entries
  fields:
    - title
    - username
    - tags
    - notes
    - url
  # whether to search in user supplied fields and file names
  extra_fields: true
  # whether regexes in the search pattern are interpreted
  allow_regex: false


# Secret key used for session cookies
# Must be at least 64 bytes long, obtained from a cryptographically secure source.
# Will be generated on the fly if not specified.
# Set a static key for sessions to survive server restarts.
session_secret_key: '22222222222222222222222222222222222222222222222222222222222222222222222222222222222222222'

listen:  '127.0.0.1'
port:    8080

# TODO
session:
    Cookie:
        # cookie session name
        cookie_name:      'KeePass4Web'
        # cookie expiry
        cookie_duration:  '1 hour'
        # session expiry, in seconds
        session_duration: 3600
        # using https cookies
        is_secure:        1
        # no javascript access
        is_http_only:     1
